# Generated by Django 5.1.1 on 2024-10-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_evento_descricao_alter_evento_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descricao',
        ),
    ]
