# Generated by Django 5.1.1 on 2024-09-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squadzone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='jogadortime',
            name='time_id',
        ),
        migrations.RemoveField(
            model_name='jogadortime',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='perfiljogo',
            name='jogo_id',
        ),
        migrations.RemoveField(
            model_name='mentoria',
            name='usuario_experiente_id',
        ),
        migrations.RemoveField(
            model_name='mentoria',
            name='usuario_novato_id',
        ),
        migrations.RemoveField(
            model_name='perfiljogo',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='time',
            name='criador_id',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='time_1_id',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='time_2_id',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='JogadorTime',
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
        migrations.DeleteModel(
            name='Mentoria',
        ),
        migrations.DeleteModel(
            name='PerfilJogo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.DeleteModel(
            name='Treino',
        ),
    ]
