# Generated by Django 5.1.1 on 2024-09-30 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('squadzone', '0002_remove_forum_usuario_id_remove_jogadortime_time_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atual', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('brincadeira', 'Brincadeira'), ('tryhard', 'Tryhard')], max_length=50)),
                ('escudo', models.ImageField(upload_to='escudos/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('nivel_reputacao', models.IntegerField(default=3)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_treino', models.DateField()),
                ('hora', models.TimeField()),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadzone.agenda')),
                ('time_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos_time_1', to='squadzone.time')),
                ('time_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos_time_2', to='squadzone.time')),
            ],
        ),
        migrations.AddField(
            model_name='time',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times_criados', to='squadzone.usuario'),
        ),
        migrations.CreateModel(
            name='PerfilJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('modalidade', models.CharField(choices=[('casual', 'Casual'), ('competitivo', 'Competitivo')], max_length=50)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='squadzone.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='squadzone.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('data_mentoria', models.DateField()),
                ('usuario_experiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_experientes', to='squadzone.usuario')),
                ('usuario_novato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_novatos', to='squadzone.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='JogadorTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=255)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='squadzone.time')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores_times', to='squadzone.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='squadzone.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_recebido', models.DateTimeField(blank=True, null=True)),
                ('usuario_enviou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_enviados', to='squadzone.usuario')),
                ('usuario_recebeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_recebidos', to='squadzone.usuario')),
            ],
        ),
    ]
