# Generated by Django 5.1.1 on 2024-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadzone', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiljogo',
            name='modalidade',
        ),
        migrations.AlterField(
            model_name='perfiljogo',
            name='tag',
            field=models.CharField(choices=[('casual', 'Casual'), ('competitivo', 'Competitivo')], max_length=50),
        ),
    ]
