# Generated by Django 5.1.1 on 2024-10-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squadzone', '0004_remove_perfiljogo_modalidade_alter_perfiljogo_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='tipo',
            new_name='tag',
        ),
    ]
