# Generated by Django 5.1.1 on 2024-10-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadzone', '0007_usuario_versenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='verEmail',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
