# Generated by Django 5.1.1 on 2024-10-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadzone', '0009_remove_usuario_senha_remove_usuario_veremail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=1513, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='verEmail',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verSenha',
            field=models.CharField(default='', max_length=255),
        ),
    ]
