# Generated by Django 5.1.1 on 2024-11-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadzone', '0014_usuario_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto_perfil',
        ),
        migrations.AddField(
            model_name='perfiljogo',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='imagens_perfil/'),
        ),
    ]
