# Generated by Django 5.1.1 on 2024-11-11 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadzone', '0015_remove_usuario_foto_perfil_perfiljogo_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amizade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Pendente', 'Pendente'), ('Bloqueio', 'Bloqueio')], max_length=50)),
                ('usuario_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizades_1', to='squadzone.usuario')),
                ('usuario_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizades_2', to='squadzone.usuario')),
            ],
        ),
    ]
