# Generated by Django 5.1.1 on 2024-11-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadzone', '0016_amizade'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='amizade',
            constraint=models.UniqueConstraint(fields=('usuario_1', 'usuario_2'), name='amizade_unica'),
        ),
    ]
