# Generated by Django 5.1.1 on 2024-11-11 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadzone', '0017_amizade_amizade_unica'),
    ]

    operations = [
        migrations.AddField(
            model_name='amizade',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
