# Generated by Django 5.1.1 on 2024-11-13 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadzone', '0022_alter_amizade_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='amizade',
            name='amizade_unica',
        ),
        migrations.AlterField(
            model_name='amizade',
            name='amigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='amizade',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aceito', 'Aceito'), ('Recusado', 'Recusado')], default='Pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='amizade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='amizade',
            unique_together={('usuario', 'amigo')},
        ),
    ]
