# Generated by Django 5.1.1 on 2024-11-22 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadzone', '0026_alter_usuario_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentoria',
            name='usuario_experiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_experientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='usuario_enviou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentoria',
            name='usuario_novato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_novatos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='usuario_recebeu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jogadortime',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores_times', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfiljogo',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='perfiljogo',
            old_name='tag',
            new_name='tipo_jogador',
        ),
        migrations.RemoveField(
            model_name='perfiljogo',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='agenda',
        ),
        migrations.AddField(
            model_name='perfiljogo',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfiljogo',
            name='jogos',
            field=models.ManyToManyField(related_name='jogadores', to='squadzone.jogo'),
        ),
        migrations.AddField(
            model_name='perfiljogo',
            name='localizacao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
