<<<<<<< Updated upstream
# Generated by Django 5.1.2 on 2024-10-15 13:18
=======
# Generated by Django 5.1.2 on 2024-10-15 12:31
>>>>>>> Stashed changes

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
<<<<<<< Updated upstream
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
=======
            field=models.ForeignKey(default=134, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
>>>>>>> Stashed changes
            preserve_default=False,
        ),
    ]
