# Generated by Django 5.1.2 on 2024-10-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
