# Generated by Django 5.1.2 on 2024-10-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
