# Generated by Django 5.1.1 on 2024-10-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
    ]
