# Generated by Django 5.1.1 on 2024-10-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='imagem_capa',
            field=models.ImageField(blank=True, upload_to='static/imagens_capa/'),
        ),
    ]
