# Generated by Django 5.1.1 on 2024-11-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_postagem_imagem_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postagem',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
