# Generated by Django 5.1.1 on 2024-11-05 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_postagem_downvotes_postagem_upvotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='upvotes',
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_voto', models.CharField(max_length=10)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.postagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'postagem')},
            },
        ),
    ]
