# Generated by Django 5.1.1 on 2024-11-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_postagem_downvotes_postagem_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='tipo_voto',
        ),
    ]
