# Generated by Django 5.1.1 on 2024-11-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_voto_tipo_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='tipo_voto',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
